repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - name: Check YAML
        id: check-yaml
      - name: Check TOML
        id: check-toml
      - name: Fix end of files
        id: end-of-file-fixer
      - name: Trim trailing whitespace
        id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - name: Lint code with Black
        id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - name: Lint imports with isort
        id: isort